//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLUB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SOCIOS
    {
        [DisplayName("Nombre")]
        [Required]
        public string NOMBRE { get; set; }

        [DisplayName("Apellidos")]
        [Required]
        public string APELLIDOS { get; set; }

        [DisplayName("Cédula")]
        [Required]
        public string CEDULA { get; set; }

        [DisplayName("Foto")]
        public byte[] FOTO { get; set; }

        [DisplayName("Dirección")]
        public string DIRECCION { get; set; }

        [DisplayName("Teléfono")]
        public string TELEFONO { get; set; }

        [DisplayName("Sexo")]
        public string SEXO { get; set; }

        [DisplayName("Edad")]
        public Nullable<int> EDAD { get; set; }

        [DisplayName("Fecha de Nacimiento")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> FECHADENAC { get; set; }

        [DisplayName("Afiliados")]
        public string AFILIADOS { get; set; }

        [DisplayName("Datos de la membresía")]
        public string DATOSMEMBRESIA { get; set; }

        [DisplayName("Lugar de trabajo")]
        public string LUGARDETRABAJO { get; set; }

        [DisplayName("Dirección de la oficina")]
        public string DIRECCIONOFICINA { get; set; }

        [DisplayName("Teléfono de la oficina")]
        public string TELOFOCINA { get; set; }

        [DisplayName("Estado de la membresía")]
        public string ESTADODEMEMBRESIA { get; set; }

        [DisplayName("Fecha de ingreso")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> FECHAINGRESO { get; set; }

        [DisplayName("Fecha de salida")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> FECHASALIDA { get; set; }
    }
}
